# Docker Compose file to train / fine-tune a pre-trained
# DeepSpeech acoustic model.
#
# DeepSpeech will use data under /DeepSpeech/deepspeech-data, which is mapped
# to the local folder ./deepspeech-data
version: "2.3"
services:
    tensorboard:
        image: tensorflow/tensorflow
        ports:
          - "6006:6006"
        volumes:
          - ./deepspeech-data/tedlium/summary:/tflogs
        command: tensorboard --host 0.0.0.0 --logdir /tflogs
    deepspeech-train:
        image: mozilla/deepspeech-train:v0.9.3
        environment:
          - NVIDIA_VISIBLE_DEVICES=0
        command: >
            python3 DeepSpeech.py
                --train_files deepspeech-data/train.csv
                --dev_files deepspeech-data/dev.csv
                --test_files deepspeech-data/test.csv
                --checkpoint_dir deepspeech-data/checkpoints
                --export_dir deepspeech-data/exported-model
                --summary_dir deepspeech-data/summary
                --train_cudnn
                --epochs 10
                --early_stop
                --n_hidden 2048
                --learning_rate 0.0001
        runtime: nvidia
        volumes:
          - ./deepspeech-data:/DeepSpeech/deepspeech-data
